# I want a job that run pnpm install and pnpm run build
# and then build de Docker image and push it to the registry
# and then deploy the app to docker-compose

variables:
  DOCKER_PRIVATE_REGISTRY: docker-internal.felipesanchezweb.es
  BASE_IMAGE_TAG: $DOCKER_PRIVATE_REGISTRY/felipesanchezweb-nuxt
  IMAGE_TAG: $BASE_IMAGE_TAG:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $BASE_IMAGE_TAG:latest

  SSH_HOST: 192.1.30.0

stages:
#  - build
  - dockerize
  - deploy

#build-nuxt-app:
#  stage: build
#  script:
#    - npm install -g pnpm
#    - pnpm install
#    - pnpm run build

dockerize-app:
  stage: dockerize
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_PRIVATE_REGISTRY
    - docker push $BASE_IMAGE_TAG --all-tags

deploy-app-in-remote-host:
  stage: deploy
  image: alpine:3.18
  before_script:
    - apk add --no-cache openssh sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no docker-compose.yaml "$SSH_USER@$SSH_HOST":docker-compose.yaml
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 
      "docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_PRIVATE_REGISTRY &&
      docker compose pull &&
      docker compose up --force-recreate --build -d"

