# I want a job that run pnpm install and pnpm run build
# and then build de Docker image and push it to the registry
# and then deploy the app to docker-compose

variables:
  DOCKER_HOST: docker-internal.felipesanchezweb.es
  IMAGE_TAG: $DOCKER_HOST.felipesanchezweb-nuxt:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $DOCKER_HOST.felipesanchezweb-nuxt:latest

stages:
#  - build
  - dockerize
  - deploy

#build-nuxt-app:
#  stage: build
#  script:
#    - npm install -g pnpm
#    - pnpm install
#    - pnpm run build

dockerize-app:
  stage: dockerize
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_HOST
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG