# I want a job that run pnpm install and pnpm run build
# and then build de Docker image and push it to the registry
# and then deploy the app to docker-compose

image: node:18-alpine
stages:
  - build
  - deploy

build-nuxt-app:
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build